apiVersion: v1
kind: Service
metadata:
  labels:
    app: failover-test2
  name: failover-test2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: failover-test2
---
apiVersion: networking.karmada.io/v1alpha1
kind: MultiClusterService
metadata:
   name: failover-test2
spec:
  types:
    - CrossCluster
  consumerClusters:
    - name: ansible2
  providerClusters:
    - name: ansible1
