apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: curl
    optimize-for: green-power
  name: test-client
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-client
  template:
    metadata:      
      labels:
        app: test-client
    spec:
      containers:
      - image: curlimages/curl
        name: curl
        command: ["sleep", "365d"]
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
--- 
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: test-client-policy
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: test-client
  placement:
    clusterAffinities:
    - affinityName: optimize-for
      labelSelector:
        matchLabels:
          optimize-for: green-power
    - affinityName: clusters
      clusterNames:
      - ansible1
      - ansible2
      - k3s-cluster
    replicaScheduling:
      replicaSchedulingType: Duplicated
    spreadConstraints:
      - spreadByField: provider
        maxGroups: 1
        minGroups: 1
      - spreadByField: cluster
        maxGroups: 1
        minGroups: 1
